version: '3'

services:

  flask_app:
    build: ./flask-app
    ports:
      - "5000:5000"
    networks:
      - global-network

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-proxy/certificates/localhost.pem:/etc/nginx/certs/localhost.pem
      - ./nginx-proxy/certificates/localhost.key:/etc/nginx/certs/localhost.key
    networks:
      - global-network

  ldap-server:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=MyCompany
      - LDAP_DOMAIN=mycompany.com
      - LDAP_ADMIN_PASSWORD=admin_password
    ports:
      - "389:389"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    networks:
      - global-network

networks:
  global-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
